//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartavya_Guntewar_Interview_Assignment.Models
{
    using System;
    using System.Collections.Generic;


    public partial class Student
    {

        public int Stud_Roll { get; set; }
        public string Stud_Name { get; set; }
        public string Stud_DOB { get; set; }
        public string Stud_Mail { get; set; }
        public string Stud_Gender { get; set; }
        public string Stud_Language { get; set; }
    }
}
